# Generated by Django 3.2.3 on 2021-06-28 06:36

import compliance.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataframe_DD_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, null=True)),
                ('noofcountsofdaysheshehavebeenworked', models.CharField(max_length=100, null=True)),
                ('summaryofdays', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dataframetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, null=True)),
                ('noofcountsofdaysheshehavebeenworked', models.CharField(max_length=100, null=True)),
                ('reportworkingdays', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=100)),
                ('contractorname', models.CharField(max_length=100)),
                ('site_projectname', models.CharField(max_length=100)),
                ('locationofwork', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('appropriategovt', models.CharField(max_length=100)),
                ('zoneapplicable', models.CharField(max_length=100)),
                ('industryapplicable', models.CharField(max_length=100)),
                ('mmyy', models.CharField(max_length=100)),
                ('salarytype', models.CharField(max_length=100)),
                ('poagreementslagreementworkorder', models.FileField(upload_to='')),
                ('poagreementslagreementworkorder_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('labourLicenseUnderCLRA', models.FileField(blank=True, null=True, upload_to='')),
                ('labourLicenseUnderCLRA_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('musterroll', models.FileField(upload_to='', validators=[compliance.validators.validate_file_extension])),
                ('registerofwages', models.FileField(upload_to='', validators=[compliance.validators.validate_file_extension])),
                ('bankstatement', models.FileField(upload_to='')),
                ('musterroll_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('registerofwages_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('bankstatement_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('EPFchallan', models.FileField(blank=True, null=True, upload_to='')),
                ('EPFchallan_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('EPFecr', models.FileField(blank=True, null=True, upload_to='')),
                ('EPFecr_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('EPFarrearchallan', models.FileField(blank=True, null=True, upload_to='')),
                ('EPFarrearchallan_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('EPFarrearecr', models.FileField(blank=True, null=True, upload_to='')),
                ('EPFarrearecr_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('ESIdoubleverificationchallan', models.FileField(blank=True, null=True, upload_to='')),
                ('ESIdoubleverificationchallan_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('ESIcontributionhistory', models.FileField(blank=True, null=True, upload_to='')),
                ('ESIcontributionhistory_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('ESIsupplementarychallanarrear', models.FileField(blank=True, null=True, upload_to='')),
                ('ESIsupplementarychallanarrear_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('ESIarrearcontributionhistory', models.FileField(blank=True, null=True, upload_to='')),
                ('ESIarrearcontributionhistory_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('WCpolicy', models.FileField(blank=True, null=True, upload_to='')),
                ('WCpolicy_status', models.CharField(blank=True, default='uncompiled', max_length=100, null=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musterroll_template', models.FileField(upload_to='')),
                ('registerwages_template', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='yes_complaines_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.file1')),
            ],
        ),
    ]
